name: gesture_vox_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  url_launcher: ^6.0.9
  webview_flutter: ^4.10.0
  webview_flutter_android: 4.3.2
  carousel_slider: ^5.0.0
  share_plus: ^7.2.1
  speech_to_text: ^6.1.1
  model_viewer_plus: ^1.6.0
  http: ^0.13.6
  http_parser: ^4.0.2
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  video_player: ^2.8.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
    - assets/images/
    - assets/svg/
    - assets/icons/
    - assets/models/gesture_character.glb
    - assets/models/